/*
 * File name: tmotor_mn4004_kv300.h
 * Description: Header file containing definitions of MN4004 KV300 motor from T-MOTOR.
 */

#ifndef __TMOTOR_MN4004_KV400_DEFINES_H__
#define __TMOTOR_MN4004_KV400_DEFINES_H__

/************************************************************************
 * INCLUDES
 ************************************************************************/
#include "../../uomodri_user_defines.h"

/***********************************************************************
 * MOTORS DEFINES
 ***********************************************************************/
#define TMOTOR_MN4004_KV400_KV                              (380.0f)    // Motor constant (rpm/V)
#define TMOTOR_MN4004_KV400_KE                              (FM_SQRT3 / (TMOTOR_MN4004_KV400_KV * FM_RPM2RADPS)) // Motor back EMF constant (V/rad/s)
#define TMOTOR_MN4004_KV400_KI                              (0.1f)      // Motor torque constant (N.m/A)
#define TMOTOR_MN4004_KV400_RS                              (0.30f)     // Stator resistance (ohm)
#define TMOTOR_MN4004_KV400_LS                              (102e-6f)   // Stator d-axis inductance (H)
#define TMOTOR_MN4004_KV400_POLES_PAIRS                     (12.0f)     // Number of poles
#define TMOTOR_MN4004_KV400_CURRENT_INIT_MAX                (2.0f)      // Current on d-axis for motor alignment (A)
#define TMOTOR_MN4004_KV400_CURRENT_CMD_SAT_MAX             (10.0f)

#define TMOTOR_MN4004_KV400_CURRENT_CUTOFF_FREQ             (1000.0f)   // Current loop bandwidth (Hz)
#define TMOTOR_MN4004_KV400_CURRENT_TIME_CONST              (FM_2MULTPI * TMOTOR_MN4004_KV400_CURRENT_CUTOFF_FREQ * PWM_PERIOD)
#define TMOTOR_MN4004_KV400_CURRENT_LPF_ALPHA               (TMOTOR_MN4004_KV400_CURRENT_TIME_CONST / (1.0f + TMOTOR_MN4004_KV400_CURRENT_TIME_CONST))
#define TMOTOR_MN4004_KV400_CURRENT_LPF_ONE_M_ALPHA         (1.0f - TMOTOR_MN4004_KV400_CURRENT_LPF_ALPHA)
#define TMOTOR_MN4004_KV400_FIX_INIT_DELAY                  (2.0f)      // in seconds
#define TMOTOR_MN4004_KV400_FIX_INIT_EVT                    (TMOTOR_MN4004_KV400_FIX_INIT_DELAY * PWM_FREQ)
#define TMOTOR_MN4004_KV400_CURRENT_INIT_DELAY              (0.5f)      // in seconds
#define TMOTOR_MN4004_KV400_CURRENT_INIT_EVT                (TMOTOR_MN4004_KV400_CURRENT_INIT_DELAY * PWM_FREQ)
#define TMOTOR_MN4004_KV400_CURRENT_INIT_STEP               (TMOTOR_MN4004_KV400_CURRENT_INIT_MAX / TMOTOR_MN4004_KV400_CURRENT_INIT_EVT)
#define TMOTOR_MN4004_KV400_POSITION_INIT_MAX               FM_2MULTPI
#define TMOTOR_MN4004_KV400_POSITION_INIT_DELAY             TMOTOR_MN4004_KV400_CURRENT_INIT_DELAY
#define TMOTOR_MN4004_KV400_POSITION_INIT_EVT               (TMOTOR_MN4004_KV400_POSITION_INIT_DELAY * PWM_FREQ)
#define TMOTOR_MN4004_KV400_POSITION_INIT_STEP              (TMOTOR_MN4004_KV400_POSITION_INIT_MAX / TMOTOR_MN4004_KV400_POSITION_INIT_EVT)
#define TMOTOR_MN4004_KV400_POSITION_INIT_ERR_MAX           ((TMOTOR_MN4004_KV400_POSITION_INIT_MAX + FM_2MULTPIDIV10) / TMOTOR_MN4004_KV400_POLES_PAIRS)
#define TMOTOR_MN4004_KV400_POSITION_INIT_ERR_MIN           ((TMOTOR_MN4004_KV400_POSITION_INIT_MAX - FM_2MULTPIDIV10) / TMOTOR_MN4004_KV400_POLES_PAIRS)
#define TMOTOR_MN4004_KV400_POSITION_INIT_ERR               (FM_2MULTPI / 10.0f / TMOTOR_MN4004_KV400_POLES_PAIRS)
#define TMOTOR_MN4004_KV400_PI_ID_KP_COEF                   (TMOTOR_MN4004_KV400_LS * FM_2MULTPI * TMOTOR_MN4004_KV400_CURRENT_CUTOFF_FREQ)
#define TMOTOR_MN4004_KV400_PI_ID_KI_COEF                   (TMOTOR_MN4004_KV400_RS * FM_2MULTPI * TMOTOR_MN4004_KV400_CURRENT_CUTOFF_FREQ)
#define TMOTOR_MN4004_KV400_PI_IQ_KP_COEF                   (TMOTOR_MN4004_KV400_LS * FM_2MULTPI * TMOTOR_MN4004_KV400_CURRENT_CUTOFF_FREQ)
#define TMOTOR_MN4004_KV400_PI_IQ_KI_COEF                   (TMOTOR_MN4004_KV400_RS * FM_2MULTPI * TMOTOR_MN4004_KV400_CURRENT_CUTOFF_FREQ)
#define TMOTOR_MN4004_KV400_DTC_MAX                         (0.9f)      // Max duty cycle
#define TMOTOR_MN4004_KV400_DTC_MIN                         (0.1f)      // Min duty cycle
#define TMOTOR_MN4004_KV400_STATOR_RESISTOR_CUTOFF_FREQ     (0.2f)
#define TMOTOR_MN4004_KV400_STATOR_RESISTOR_TIME_CONST      (FM_2MULTPI * TMOTOR_MN4004_KV400_STATOR_RESISTOR_CUTOFF_FREQ * PWM_PERIOD)
#define TMOTOR_MN4004_KV400_STATOR_RESISTOR_LPF_ALPHA       (TMOTOR_MN4004_KV400_STATOR_RESISTOR_TIME_CONST / (1.0f + TMOTOR_MN4004_KV400_STATOR_RESISTOR_TIME_CONST))
#define TMOTOR_MN4004_KV400_STATOR_RESISTOR_LPF_ONE_M_ALPHA (1.0f - TMOTOR_MN4004_KV400_STATOR_RESISTOR_LPF_ALPHA)

/*** Motor 1 constants ***/
#if (MOTOR1_PARAMS == USE_TMOTOR_MN4004_KV400)
#define MOTOR1_KV                                           TMOTOR_MN4004_KV400_KV
#define MOTOR1_KE                                           TMOTOR_MN4004_KV400_KE
#define MOTOR1_KI                                           TMOTOR_MN4004_KV400_KI
#define MOTOR1_RS                                           TMOTOR_MN4004_KV400_RS
#define MOTOR1_LS                                           TMOTOR_MN4004_KV400_LS
#define MOTOR1_POLES_PAIRS                                  TMOTOR_MN4004_KV400_POLES_PAIRS
#define MOTOR1_CURRENT_INIT_MAX                             TMOTOR_MN4004_KV400_CURRENT_INIT_MAX
#define MOTOR1_CURRENT_CMD_SAT_MAX                          TMOTOR_MN4004_KV400_CURRENT_CMD_SAT_MAX

#define MOTOR1_CURRENT_CUTOFF_FREQ                          TMOTOR_MN4004_KV400_CURRENT_CUTOFF_FREQ
#define MOTOR1_CURRENT_TIME_CONST                           TMOTOR_MN4004_KV400_CURRENT_TIME_CONST
#define MOTOR1_CURRENT_LPF_ALPHA                            TMOTOR_MN4004_KV400_CURRENT_LPF_ALPHA
#define MOTOR1_CURRENT_LPF_ONE_M_ALPHA                      TMOTOR_MN4004_KV400_CURRENT_LPF_ONE_M_ALPHA
#define MOTOR1_FIX_INIT_DELAY                               TMOTOR_MN4004_KV400_FIX_INIT_DELAY
#define MOTOR1_FIX_INIT_EVT                                 TMOTOR_MN4004_KV400_FIX_INIT_EVT
#define MOTOR1_CURRENT_INIT_DELAY                           TMOTOR_MN4004_KV400_CURRENT_INIT_DELAY
#define MOTOR1_CURRENT_INIT_EVT                             TMOTOR_MN4004_KV400_CURRENT_INIT_EVT
#define MOTOR1_CURRENT_INIT_STEP                            TMOTOR_MN4004_KV400_CURRENT_INIT_STEP
#define MOTOR1_POSITION_INIT_MAX                            TMOTOR_MN4004_KV400_POSITION_INIT_MAX
#define MOTOR1_POSITION_INIT_DELAY                          TMOTOR_MN4004_KV400_CURRENT_INIT_DELAY
#define MOTOR1_POSITION_INIT_EVT                            TMOTOR_MN4004_KV400_POSITION_INIT_EVT
#define MOTOR1_POSITION_INIT_STEP                           TMOTOR_MN4004_KV400_POSITION_INIT_STEP
#define MOTOR1_POSITION_INIT_ERR_MAX                        TMOTOR_MN4004_KV400_POSITION_INIT_ERR_MAX
#define MOTOR1_POSITION_INIT_ERR_MIN                        TMOTOR_MN4004_KV400_POSITION_INIT_ERR_MIN
#define MOTOR1_POSITION_INIT_ERR                            TMOTOR_MN4004_KV400_POSITION_INIT_ERR
#define MOTOR1_PI_ID_KP_COEF                                TMOTOR_MN4004_KV400_PI_ID_KP_COEF
#define MOTOR1_PI_ID_KI_COEF                                TMOTOR_MN4004_KV400_PI_ID_KI_COEF
#define MOTOR1_PI_IQ_KP_COEF                                TMOTOR_MN4004_KV400_PI_IQ_KP_COEF
#define MOTOR1_PI_IQ_KI_COEF                                TMOTOR_MN4004_KV400_PI_IQ_KI_COEF
#define MOTOR1_DTC_MAX                                      TMOTOR_MN4004_KV400_DTC_MAX
#define MOTOR1_DTC_MIN                                      TMOTOR_MN4004_KV400_DTC_MIN
#define MOTOR1_STATOR_RESISTOR_CUTOFF_FREQ                  TMOTOR_MN4004_KV400_STATOR_RESISTOR_CUTOFF_FREQ
#define MOTOR1_STATOR_RESISTOR_TIME_CONST                   TMOTOR_MN4004_KV400_STATOR_RESISTOR_TIME_CONST
#define MOTOR1_STATOR_RESISTOR_LPF_ALPHA                    TMOTOR_MN4004_KV400_STATOR_RESISTOR_LPF_ALPHA
#define MOTOR1_STATOR_RESISTOR_LPF_ONE_M_ALPHA              TMOTOR_MN4004_KV400_STATOR_RESISTOR_LPF_ONE_M_ALPHA
#endif /* USE_TMOTOR_MN4004_KV400_ON_MOTOR1 */

/*** Motor 2 constants ***/
#if (MOTOR2_PARAMS == USE_TMOTOR_MN4004_KV400)
#define MOTOR2_KV                                           TMOTOR_MN4004_KV400_KV
#define MOTOR2_KE                                           TMOTOR_MN4004_KV400_KE
#define MOTOR2_KI                                           TMOTOR_MN4004_KV400_KI
#define MOTOR2_RS                                           TMOTOR_MN4004_KV400_RS
#define MOTOR2_LS                                           TMOTOR_MN4004_KV400_LS
#define MOTOR2_POLES_PAIRS                                  TMOTOR_MN4004_KV400_POLES_PAIRS
#define MOTOR2_CURRENT_INIT_MAX                             TMOTOR_MN4004_KV400_CURRENT_INIT_MAX
#define MOTOR2_CURRENT_CMD_SAT_MAX                          TMOTOR_MN4004_KV400_CURRENT_CMD_SAT_MAX

#define MOTOR2_CURRENT_CUTOFF_FREQ                          TMOTOR_MN4004_KV400_CURRENT_CUTOFF_FREQ
#define MOTOR2_CURRENT_TIME_CONST                           TMOTOR_MN4004_KV400_CURRENT_TIME_CONST
#define MOTOR2_CURRENT_LPF_ALPHA                            TMOTOR_MN4004_KV400_CURRENT_LPF_ALPHA
#define MOTOR2_CURRENT_LPF_ONE_M_ALPHA                      TMOTOR_MN4004_KV400_CURRENT_LPF_ONE_M_ALPHA
#define MOTOR2_FIX_INIT_DELAY                               TMOTOR_MN4004_KV400_FIX_INIT_DELAY
#define MOTOR2_FIX_INIT_EVT                                 TMOTOR_MN4004_KV400_FIX_INIT_EVT
#define MOTOR2_CURRENT_INIT_DELAY                           TMOTOR_MN4004_KV400_CURRENT_INIT_DELAY
#define MOTOR2_CURRENT_INIT_EVT                             TMOTOR_MN4004_KV400_CURRENT_INIT_EVT
#define MOTOR2_CURRENT_INIT_STEP                            TMOTOR_MN4004_KV400_CURRENT_INIT_STEP
#define MOTOR2_POSITION_INIT_MAX                            TMOTOR_MN4004_KV400_POSITION_INIT_MAX
#define MOTOR2_POSITION_INIT_DELAY                          TMOTOR_MN4004_KV400_CURRENT_INIT_DELAY
#define MOTOR2_POSITION_INIT_EVT                            TMOTOR_MN4004_KV400_POSITION_INIT_EVT
#define MOTOR2_POSITION_INIT_STEP                           TMOTOR_MN4004_KV400_POSITION_INIT_STEP
#define MOTOR2_POSITION_INIT_ERR_MAX                        TMOTOR_MN4004_KV400_POSITION_INIT_ERR_MAX
#define MOTOR2_POSITION_INIT_ERR_MIN                        TMOTOR_MN4004_KV400_POSITION_INIT_ERR_MIN
#define MOTOR2_POSITION_INIT_ERR                            TMOTOR_MN4004_KV400_POSITION_INIT_ERR
#define MOTOR2_PI_ID_KP_COEF                                TMOTOR_MN4004_KV400_PI_ID_KP_COEF
#define MOTOR2_PI_ID_KI_COEF                                TMOTOR_MN4004_KV400_PI_ID_KI_COEF
#define MOTOR2_PI_IQ_KP_COEF                                TMOTOR_MN4004_KV400_PI_IQ_KP_COEF
#define MOTOR2_PI_IQ_KI_COEF                                TMOTOR_MN4004_KV400_PI_IQ_KI_COEF
#define MOTOR2_DTC_MAX                                      TMOTOR_MN4004_KV400_DTC_MAX
#define MOTOR2_DTC_MIN                                      TMOTOR_MN4004_KV400_DTC_MIN
#define MOTOR2_STATOR_RESISTOR_CUTOFF_FREQ                  TMOTOR_MN4004_KV400_STATOR_RESISTOR_CUTOFF_FREQ
#define MOTOR2_STATOR_RESISTOR_TIME_CONST                   TMOTOR_MN4004_KV400_STATOR_RESISTOR_TIME_CONST
#define MOTOR2_STATOR_RESISTOR_LPF_ALPHA                    TMOTOR_MN4004_KV400_STATOR_RESISTOR_LPF_ALPHA
#define MOTOR2_STATOR_RESISTOR_LPF_ONE_M_ALPHA              TMOTOR_MN4004_KV400_STATOR_RESISTOR_LPF_ONE_M_ALPHA
#endif /* USE_TMOTOR_MN4004_KV400_ON_MOTOR2 */

#endif /* __TMOTOR_MN4004_KV400_DEFINES_H__ */
