M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu22.04.1} date 2024-10-24T18:11:12+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-24T18:11:12+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X172.0Y-131.1
T2
X141.215Y-140.598
X148.104Y-142.315
M30
